{% set name = "consul" %}
{% set version = "1.0.0" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  fn: {{ name }}-{{ version }}.zip
  sha256: b2980101554e9ace4c0d56e1d27ab574d166db6625a91d1157a7c41de299313b  # [osx]
  sha256: da0642f2d68957d33b67c7ec4ede4d17ead3d4551fc562322a190a98a6f6dceb  # [linux32]
  sha256: 585782e1fb25a2096e1776e2da206866b1d9e1f10b71317e682e03125f22f479  # [linux64]
  sha256: b7415bb29eb56289b6bfa1a39638f55ba88fb443482d1c98ba79e86222f0b5c7  # [win32]
  sha256: 3b65661d4cd0336f8c15b0edee483235c7d2025c987e95164ce7fa77ded3e16d  # [win64]

build:
  number: {{ build_number }}

test:
  commands:
    - consul -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your 
    infrastructure. It provides several key features, including: 
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and 
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
