{% set import_path = "github.com/hashicorp/consul" %}
{% set version = "1.4.2" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = 'src' + os.sep+ import_path.replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    git_url: https://{{ import_path }}
    git_tag: v{{ version }}
    url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [false]
    sha256: 1ee8652e053dda0538a1f7886a856d0a825ec778217082f21aaba096220a1f98  # [false]

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your
    infrastructure. It provides several key features, including:
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
