{% set name = "consul" %}
{% set version = "0.8.3" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  fn: {{ name }}-{{ version }}.zip
  sha256: 97102020bd3638e98d65633d0e51d425168de17a53f12d566585663a2a19905f  # [osx]
  sha256: f4c6cdf82de7aacbac1590d46f755ddb4861894cc78753a9b29ef351abaa748c  # [linux32]
  sha256: f894383eee730fcb2c5936748cc019d83b220321efd0e790dae9a3266f5d443a  # [linux64]
  sha256: c9a6f92b34eab0ceec854830af4c906339737c0df0f4875c03da9ac7031fe56e  # [win32]
  sha256: 9fea45cbe7e55bb94b3d7fb4c8f0527ba36c79029eb1369ace0d45d9546d158a  # [win64]

build:
  number: {{ build_number }}

test:
  commands:
    - consul -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your 
    infrastructure. It provides several key features, including: 
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and 
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
