{% set name = "consul" %}
{% set version = "1.0.3" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  fn: {{ name }}-{{ version }}.zip
  sha256: d3999f80d3083ceee800ef8d0cf06dbe88d0449d4056203bd2f7491218b99d1d  # [osx]
  sha256: f44d255d5a5126f95698cebc561a76f0824e9b53d391f84d0501d8ef36facbae  # [linux32]
  sha256: 4782e4662de8effe49e97c50b1a1233c03c0026881f6c004144cc3b73f446ec5  # [linux64]
  sha256: 1beb71cf1da5563d1dc05beb309b6a3bb2a884733bf8f9a9c3a851d148691712  # [win32]
  sha256: 287581af4f30a19921bb6c3c4d80282dddae7e8ccced135366af83358e3f62a5  # [win64]

build:
  number: {{ build_number }}

test:
  commands:
    - consul -v

about:
  home: https://www.consul.io
  license: MPL 2.0
  summary: Service discovery and configuration made easy.
  description: |
    Consul is a tool for discovering and configuring services in your 
    infrastructure. It provides several key features, including: 
    Service Discovery, Health Checking, KV Store, Multi Datacenter.
    Consul is designed to be friendly to both the DevOps community and 
    application developers, making it perfect for modern, elastic infrastructures.

  doc_url: https://www.consul.io/docs/index.html

extra:
  recipe-maintainers:
    - sodre
