travis:
  secure:
    BINSTAR_TOKEN: Auao17Ll4oiUR1Nwais03igDl9SwjLA6ZS9XLlf14zZ8EYLUjm1yai4HMuN2CIDvhS8ejLpw8J4RHhwRaHprHaNf+DiSb0fdHebbTU3l0tKzbiXPZezWz+8qV4ctY9EvVyWd3r4eaoA3yoPgmXBbI04rr1apjuK8ZDKZyIs8+HvBRWrHnTA3LJwpB+lk9LfZxfuoODZjUSHysm0zR3LMrHQHvZoOqvkZ6LqpkhmTYvz8gkJ0sLXOuOun1T4PYnVl5srgR5pkr2jp5BOrV8nkbslUs7uZ9cLfZstOcbKRPtY6hD03MLhHi0ps3P1gAZEItvEiAhNZvkV1MdnCVj9/Dt9DXfzXSFme/Djb0dDEKp/oLzaiebm1EBdwoTcEugWx+Guc7saN9TyLlL6UL6Jv4NW2W2ZK4W5ZgBk4d/RqpLT0JcbhsKdpdO8DiMrY8zkaidhPGZkxCMSHwqyVnZQ9PYrQSkN/rr6OAbTKjTT2TPO2BScXCL/gF2Xx8t2fGuV59LCDOVUvteIEvUtG/shIxcdISBV80JGlJuQsbfS/MIhqwgTggTqcO0yfxQ/y6Njp94fByVCIZCjMKDInQTANusxth2KBSi2hvWlV/67oukJKhNutsJwfbLBH2HeQmmOb87HbrIgAknt9E/YcEktbXfpHUmqztjXvoasK4aegOVg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
