travis:
  secure:
    BINSTAR_TOKEN: l/J1/BOQhaYzaxbZfCbPnYZVg6B0weOjxD2JZYwKKwfKNwI73kAFI1XwmOlEc6Ug7pdhkdm47ok71NQPAKEm0ejOiDJ8uEP0EXukZA3IjPQb8EXGYPmu4AbGQgWBmtZYx1xdh5yk+wmnW2jzOqVsZxk3psId7h9mA0zfbDb2XTL6jetYsZcSMHEu5caYLEycfY+GXmtjOwwddSYNFA1PiEuZ+JB5LuWRZu/szXyWmGX+/KR50eRLI7iQb+t0zCntemub49jkozejGAUmf1Hf7993EdtQYkUXKkj2jTn0Z/gubSBOqGMgd24zrL7i6ABMY6m3X4OlnpafWhPHjQ9K2MAPuAXk5zgVO9rncRZodQAALqBqo9QCs5kNsJSItGFpA4UxbB+fBGK7Lwz5Ff7DpeJraatz/aJXj/xgLguWBFDhsPRO7wqdjDPFlyA0nu8ZD6N+iD4HD7unh6AgZJPSc8dZBzO1lELmXYRqzqWqiafbtJwHrar6Jh7iWSQx49d3uLJiCCssPSOAcD3SMa6KUJZnM9KkSIkMXj6FhRg9ip5Ewg8w6FHJgrgZ8OEo8qnTqzrwtaeAAYKyUpG/ByO9K4mSCLzFMobOKyiH2RxKFhAogxd5vY4r/J2UWJClAnMmXowYKJNOUvMCZzxejKzU+Ftd4JwsYvJ6jGCjO7TlphI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
