travis:
  secure:
    BINSTAR_TOKEN: PNze5c/QeTpu4vMfNxCxd/m8WPid9uDkwZHqS6rlt/uM9MD2yYLMK8y6OggWqe16INiEVe2BX0DZFjMCjhi3m9R5bHGNW6arJL0LwG7itD4xalyJPtsNuwzxojd7BQ9kFX4IFhrw9TQp3iYa8t5Wixd9pfiln13C2R20tQTbGBH+Ap1ORSqAXxGjlN9gsJKpzJDr4m1r7MkI0Br+EjnlJk/QxE5mePm28YoJhsb1EFNpCA6qeCX7c6Xw7pAjNL+mLvaMD7oXYQbvlJru9SPDcfo9n7rCtxjTOry1T4OX95qRrvpNUstZ0tCGgTYyeGHbbuccdoI1y3rS4HMxNbWVHSy8/8ZdPFN+KLOuSCrr7urqyCRs/YcOHCSDO5lWD8EFGbSkPLkNE3WlpTtnVXEIQiRAcMLTBo44NCeWAuLr64BOxDCDNrWdHV58SRz0EmT//onI7i2J+T/us7ADJ9HlotkQFENLpMaP+bPKLiQKnq/RXnBBUoe/DWF29twWXXCXSzWkHqbHLFOomG83U4Ckds7fmCb8h/4AhcUPqJ59IGcZwrahwH2wOHJf3nLmK4vEwfifwxYDlV5EHnbx/TX8dLrtZc5dJH+o6Kmkl6LEcyKK1PMybSJRRRyNG4M/7BZ1EsnBJUOojol4jN8LEsYN4kv8yZPRu8LQCQ6AjdcC6q0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
