travis:
  secure:
    BINSTAR_TOKEN: ecBaq2OZRBY7MXE7/vQINID5uWU/Z3Q4xLK1yZlv6z45kldxKMJOVFJVi0vqfIzyzx0iiOMPVnQ/iMnhoUqLOP/Jfak3iVuOYDr/47PPyisYP6RCGYlenY5o28whlT5M0gLp5amd1nlvjGMFSP3pP7yAr3R050e+V8r4pUJbWxtBBMULtIAEsaUmynNpiCGlgpmAq49bl+fG93LmtPIBZctDNlpSjBYU9bX0q+U3BDtMEbYQEiI5XNeK4Z94/h45xp3zo2kRpij4r7BDzuMHs6QblpkuqSd5sYLUgJmVZOSsgYkoH2L0eHl08A1XIy3/rnsWBKgDia6IMmozKj2M9AzwTalSqOJlx+J8bF/ckgbg/EFWr0jr74TTxcuzEKBhagoE6Ia0UP3qglf/3eAHIehG4L27fv8swMp6xQ3BpuC+KQYNHM6N1slkmrOQatKR8dE8bFfKl0NrDDJtVTzegtRtdcCXfqurKKtYG5fQ5Izkskg//rNxTsNKvTs0v5Nq8DS1UUZcER+mVWMG6RLgfuEXYv1lz9X1YmLXQr9d8/3mm+mFDCns+uf4A8joyreX9u0b+p2lsDHxlqnN10eTOJBTVj9Wi3pX3cjkb/TiXMMBCV2RQcZQ7MkNSqayD3nPk9eFkC6HZs2up+pGTibYvlxRHdYCpJiQBZn9Ng0oG/4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
