travis:
  secure:
    BINSTAR_TOKEN: tJpKARI40LMI3ZhSNBogfEhoM2pcnEIDFbAWU1GNwghqm94z9TdEOs5EbSH+b1L+ymVcXsqbVQAxvlrWeQl0paA+c+pRgjW3gg9bzHoZp5WvMHIS0hX38ym76kAhoM+frSUpZVvDJbC2yZLpmCj+OZmMNuSN+nMI53rxJbRzgEtPqUL8kyA2o/KQgMkK8IxpgSC65TLVyjUkOL406lX22KrZdZSqHTaYkKQyd7+sGMrzOoIK64W2cvsYnsaVTMEsrGkjJMosR7j/P5uhAlagGTlRihA/sMKPWTme5SSWb4Ndo3e+XN9upjUtrqLmg5F0HpoQrHsKrO+l4uHwYP8OObqwq22I48qmcPyK/EC/7JxxNukq5mnqAoeHgBLGtNQiPzOR1tSjU3hw+QPChI2Gp3QdH0tbAGxPpv96wt0YSYP4mJ3xwGN1ZOGBDvsFF0o2GbxVGhsm8remguiTMnrhXclZTXsleG4ohW15XxA9h1+guUvbZUAZzlPgBGs8WXaoC5YfCE2OFn0Z1fjTw+ui3vZSPGRHcAV1bhYlvmsOAMI547+gZOzeo8txWSMGFTfeA++f3f9VRXe3Y4nzmuHBLXaoFO2m4ux9z7LSv1dTsSBFbh6vTae1kqNY51BU6DBme8Y4NY4Hl9yxHwd3DshSD+cf4oQfRo/xevx6y7IYR6o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
